version: '3.7'

networks:
  default:

services:
  redis:
    image: 'redis:5-alpine'

  node:
    image: ${WALLET_IMAGE}
    depends_on:
      - redis
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0

