version: '3.7'

networks:
  default:

volumes:
  redis:
  certs:

services:
  nginx:
    image: ${NGINX_IMAGE}
    deploy:
      mode: global
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - certs:/etc/certs
    depends_on:
      - node

  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

  node:
    image: ${WALLET_IMAGE}
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
