version: '3.7'

volumes:
  redis:
  certs:
  config:

networks:
  default:

services:
  nginx:
    image: 'nginx:1.17-alpine'
    deploy:
      mode: global
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - certs:/etc/letsencrypt
      - config:/etc/nginx/sites-enabled/
    links:
      - proxy:proxyNodeDocker

  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data
    depends_on:
      - nginx

  proxy:
    image: ${WALLET_IMAGE}
    depends_on:
      - redis
    links:
      - redis:redisDocker
    env_file:
      - prod.env

