version: '3.7'

volumes:
  redis:
  certs:
  nginx:

networks:
  default:

services:
  nginx:
    image: ${NGINX_IMAGE}
    environment:
      DOMAIN_URL: ${BRIDGE_URL}
      NODE_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      NODE_DOCKER_NAME: node
    deploy:
      mode: global
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - certs:/etc/letsencrypt
      - nginx:/etc/nginx

  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

  node:
    image: ${WALLET_IMAGE}
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
